### ISSUE TITLE
How can I train my own video data? Great job, looking forward to your reply!

### ISSUE THREAD

**Issue by Jeff-Fudan** [Boese0601/MagicDance#10]

**Comment by Boese0601** [comment]
For training on your own dataset, you first need to run openpose for your input images/videos and organize them as the format shown in TikTok dataset. 

```bash
Your Dataset
|----train_set
  |----video_000
    |----000.jpg
    |----001.jpg
    |----002.jpg
    ...
  |----video_001
  |----video_002
  ...
|----pose_map_train_set
  |----video_000
    |----000.jpg
    |----001.jpg
    |----002.jpg
    ...
  |----video_001
  |----video_002
  ...
|----val_set
|----pose_map_val_set
|----test_set
|----pose_map_test_set
|----...
```

Then set the path to your datain [dataset/tiktok_video_arnold_copy.py](https://github.com/Boese0601/MagicDance/blob/main/dataset/tiktok_video_arnold_copy.py#L287)
