### ISSUE TITLE
I am very interested in the Multi-Source Self-Attention mentioned in the paper. Can you tell me in which script of the open-source code it can be found?

### ISSUE THREAD

**Issue by Jeff-Fudan** [Boese0601/MagicDance#13]

**Comment by Boese0601** [comment]
See [here ](https://github.com/Boese0601/MagicDance/blob/main/model_lib/ControlNet/ldm/modules/attention.py#L253)

**Comment by Jeff-Fudan** [comment]
> See [here ](https://github.com/Boese0601/MagicDance/blob/main/model_lib/ControlNet/ldm/modules/attention.py#L253)

thanks！

**Comment by Jeff-Fudan** [comment]
> See [here ](https://github.com/Boese0601/MagicDance/blob/main/model_lib/ControlNet/ldm/modules/attention.py#L253)

Can you point out the location of Equation (3) from the paper in the code? It's the concatenation operation, and it's crucial.

**Comment by Boese0601** [comment]
[Here](https://github.com/Boese0601/MagicDance/blob/main/model_lib/ControlNet/ldm/modules/attention.py#L307)

**Comment by RhythmJnh** [comment]
I compared the difference with Magicanimate and found that this implementation is the same as Magicanimate. Is this actually the case?
