### ISSUE TITLE
It seems that the Dataloader is performing slower than expected. When I train using Moore's open-source AnimateAnyone code, I have noticed that the GPU utilization reaches around 90%. However, when using MagicPose, the GPU utilization is only around 20%. I have a dataset of approximately 3K videos.

### ISSUE THREAD

**Issue by Jeff-Fudan** [Boese0601/MagicDance#14]

**Comment by Jeff-Fudan** [comment]
During the training process with MagicPose, the GPU frequently experiences waiting time for batch loading.

**Comment by Boese0601** [comment]
Probably you should consider increasing ur num_workers to 8 or more, the default is 1. I don't know too much about how to accelerate the training since this is implemented by myself using pytorch dataloader instead of original internal pkg of ByteDance.

**Comment by Jeff-Fudan** [comment]
> Probably you should consider increasing ur num_workers to 8 or more, the default is 1. I don't know too much about how to accelerate the training since this is implemented by myself using pytorch dataloader instead of original internal pkg of ByteDance.

Well, I have set the num_workers to 8 for both MagicPose and when running Moore's open-source code. However, the speed of MagicPose is noticeably slower compared to Moore's code.
