### ISSUE TITLE
I want to infer the results of the first stage, how should I proceed?

### ISSUE THREAD

**Issue by Jeff-Fudan** [Boese0601/MagicDance#15]

**Comment by Jeff-Fudan** [comment]
Can you provide some details about the inference process using only first-order weights? This is important to me. Thank you!

**Comment by Jeff-Fudan** [comment]
Can you provide some details about the inference process using only first-stage weights? This is important to me. Thank you!

**Comment by Boese0601** [comment]
Please set --model_config to model_lib/ControlNet/models/cldm_v15_reference_only.yaml and --image_pretrain_dir to your model checkpoint in [the inference script](https://github.com/Boese0601/MagicDance/blob/main/scripts/inference_tiktok_dataset.sh). You may also need to modify the ckpt loading function [here](https://github.com/Boese0601/MagicDance/blob/main/test_tiktok.py#L392)
