### ISSUE TITLE
Testing data for TikTok

### ISSUE THREAD

**Issue by notorious-eric** [Boese0601/MagicDance#3]
Hi,

In your paper you mentioned, "To ensure videos from the same person (same identity with same/different appearance) are not present in both training and testing splits, we follow [65] and use their 10 TikTok-style videos depicting different people from the web as the testing split."  I did not find the 10 videos from DisCo, and it looks like they have additional data for evaluation. I wonder how did you test the TikTok dataset? Thank you.

**Comment by Boese0601** [comment]
Hi, the evaluation data is open-sourced in the tsv file of DisCo which contains 8 self-collected sequences and 2 video sequences from TikTok. Please follow their PyTorch dataloader in the code to obtain the images and pose maps.

**Comment by notorious-eric** [comment]
thank you, I will take a look.
