### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [Boese0601/MagicDance#8]
First of all, thank you for selflessly sharing the code and pre-trained models
When I execute the following command： bash scripts/inference_tiktok_dataset.sh
I received an error message：
![image](https://github.com/Boese0601/MagicDance/assets/36565076/4e401e14-9040-4ba8-ab97-cb62130e550a)

Is there a problem with my environment, such as the version of pytorch？
Looking forward to your reply

**Comment by Boese0601** [comment]
This is a path error, please double check your directory to the pretrained models. It should be “./pretrained_weights” instead of “pretrained_weighs”

**Comment by zcdliuwei** [comment]
Please ask again, as shown in the picture below, my parameter address seems to be correct：
![image](https://github.com/Boese0601/MagicDance/assets/36565076/2f3653d1-62cc-4570-9392-c58b72a937ab)
